# Link the MSVC runtime statically so the .exe files run on a bare Windows
# (including Nano Server) without the Visual C++ redistributable.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
